/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtlasRouteImport } from './routes/atlas'
import { Route as BriefRouteImport } from './routes/brief'
import { Route as DossierRouteImport } from './routes/dossier'
import { Route as LionRouteImport } from './routes/lion'
import { Route as TemplarsRouteImport } from './routes/templars'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasRoute = AtlasRouteImport.update({
  id: '/atlas',
  path: '/atlas',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefRoute = BriefRouteImport.update({
  id: '/brief',
  path: '/brief',
  getParentRoute: () => rootRouteImport,
} as any)
const DossierRoute = DossierRouteImport.update({
  id: '/dossier',
  path: '/dossier',
  getParentRoute: () => rootRouteImport,
} as any)
const LionRoute = LionRouteImport.update({
  id: '/lion',
  path: '/lion',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplarsRoute = TemplarsRouteImport.update({
  id: '/templars',
  path: '/templars',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/brief': typeof BriefRoute
  '/dossier': typeof DossierRoute
  '/lion': typeof LionRoute
  '/templars': typeof TemplarsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/brief': typeof BriefRoute
  '/dossier': typeof DossierRoute
  '/lion': typeof LionRoute
  '/templars': typeof TemplarsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/brief': typeof BriefRoute
  '/dossier': typeof DossierRoute
  '/lion': typeof LionRoute
  '/templars': typeof TemplarsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/atlas' | '/brief' | '/dossier' | '/lion' | '/templars'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/atlas' | '/brief' | '/dossier' | '/lion' | '/templars'
  id:
    '__root__' | '/' | '/atlas' | '/brief' | '/dossier' | '/lion' | '/templars'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtlasRoute: typeof AtlasRoute
  BriefRoute: typeof BriefRoute
  DossierRoute: typeof DossierRoute
  LionRoute: typeof LionRoute
  TemplarsRoute: typeof TemplarsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas': {
      id: '/atlas'
      path: '/atlas'
      fullPath: '/atlas'
      preLoaderRoute: typeof AtlasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brief': {
      id: '/brief'
      path: '/brief'
      fullPath: '/brief'
      preLoaderRoute: typeof BriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dossier': {
      id: '/dossier'
      path: '/dossier'
      fullPath: '/dossier'
      preLoaderRoute: typeof DossierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lion': {
      id: '/lion'
      path: '/lion'
      fullPath: '/lion'
      preLoaderRoute: typeof LionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templars': {
      id: '/templars'
      path: '/templars'
      fullPath: '/templars'
      preLoaderRoute: typeof TemplarsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtlasRoute: AtlasRoute,
  BriefRoute: BriefRoute,
  DossierRoute: DossierRoute,
  LionRoute: LionRoute,
  TemplarsRoute: TemplarsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
